//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbliletisim
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz")]
        public string Adsoyad { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
        public string Konu { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
        public string Mesaj { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
